id: P7761C2AB
initial_creation_type: ocr
source_metadata:
  volumes:
    8ee394e34f704917a6cbadf88752d3c1:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: མཛད་པ་བཅུ་གཉིས་ཀྱི་ཚུལ་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
